version: '3.8'

services:
  api:
    build: .
    expose:
      - "3000"
    environment:
      - DB_HOST=98.95.177.156
      - DB_USER=ale
      - DB_PASSWORD=Lagartija20
      - DB_NAME=stylepin
      - HOST=0.0.0.0
      - PORT=3000
      - DEBUG=false
      - APP_NAME=Amura API
      - APP_VERSION=1.0.0
      - JWT_SECRET_KEY=tu-secret-key-segura-cambiar-en-produccion
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
      - CORS_ORIGINS=["*"]
      - CLOUDINARY_CLOUD_NAME=tu-cloud-name
      - CLOUDINARY_API_KEY=tu-api-key
      - CLOUDINARY_API_SECRET=tu-api-secret

    restart: always

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api

volumes:
  caddy_data:
  caddy_config: